### ISSUE TITLE
How can I get in touch with you?

### ISSUE THREAD

**Issue by XPMai** [geebips/testing#1]
I see that you have relevant expertise to Craigbot.

**Comment by geebips** [comment]
I'm sorry for late reply, I'm not here for support of any kind.

**Comment by XPMai** [comment]
> I'm sorry for late reply, I'm not here for support of any kind.

Including paid work?

**Comment by geebips** [comment]
> > I'm sorry for late reply, I'm not here for support of any kind.
> 
> Including paid work?

Correct.
